### ISSUE TITLE
strips around center in qm

### ISSUE THREAD

**Issue by karen33** [biocatiit/musclex#13]
There have strips around the center after I qm. I played the mask threshold from 0-10 and the strips still there. The image attached is mask threshold 0 using 2D conveshull background subtraction. zoom in the image and set max intensity to 100 then you will see the strips. I also attach the images to show you how it looks.  Thanks for you quick response and the program works pretty well and very easy to use. 

Karen

![screenshot from 2018-02-23 22-24-53](https://user-images.githubusercontent.com/36778564/36626479-69693346-18e8-11e8-9f53-14c754c8b97b.png)
[pwmhc2day2-4_0010_0089.zip](https://github.com/biocatiit/musclex/files/1754095/pwmhc2day2-4_0010_0089.zip)
[pwmhc2day2-4_0010_0089_folded.zip](https://github.com/biocatiit/musclex/files/1754096/pwmhc2day2-4_0010_0089_folded.zip)

**Comment by jiranun** [comment]
Hi Karen,

I will check it tomorrow. Thanks for letting me know. However, I encourage you to use Circularly Background Subtraction instead as 2D Convex hull might produce over subtracted.

Thanks,
Jiranun

**Comment by jiranun** [comment]
Hi Karen,

I'm not sure what did you mean by the 'strip'. Do you mean the black ring or the white ring around the center? (Yellow or red ring?)

![screen shot 2018-03-01 at 11 10 27 am](https://user-images.githubusercontent.com/13938351/36826641-5b8f49ba-1d41-11e8-8ef7-1db23995c3ae.png)

If you meant the white ring, it seems like the strip is there with the original image. I use fit2D to get the 1d-projection and saw a little bump at the ring position. 

Please let me know if I understood correctly, and could you please check the original image again?

Thanks.
Jiranun

**Comment by jiranun** [comment]
This is what I saw on fit2d (original image)
![screen shot 2018-03-01 at 11 14 11 am](https://user-images.githubusercontent.com/13938351/36826737-20630f2e-1d42-11e8-8372-dda72956e313.png)
![screen shot 2018-03-01 at 11 14 26 am](https://user-images.githubusercontent.com/13938351/36826740-21e229ac-1d42-11e8-80f9-1eec866bffce.png)

**Comment by karen33** [comment]
Please see the pic. I circled those strips. There were coming after quadrant folding.  

![xray](https://user-images.githubusercontent.com/36778564/36830389-4b02e3a4-1cd8-11e8-9940-b25182332e59.png)

**Comment by karen33** [comment]
I attach you another photo which shows for clearly about those strips. 
![pwmhc2day2-5](https://user-images.githubusercontent.com/36778564/36830610-384f5b24-1cd9-11e8-9e4e-0d3e94c5787e.jpg)

**Comment by jiranun** [comment]
Hi,

Normally, if there’s a black strip, quadrant folding will go to each pixel and fill that pixel by using average value of other pixels which are at the same position on other quadrants. It’s possible that the intensities on other quadrants are different from the quadrant which has the strip. That’s why we still see that the area around the strip and the strip have different intensity.

We faced this problem before and still don’t have the solution right now as the main purpose of Quadrant folding is to average 4 quadrants (Filling strips is not perfect). 

However, I will talk to Tom about this again.

Thank you,
Jiranun
