### ISSUE TITLE
minor modification

### ISSUE THREAD

**Issue by WeikangMa** [biocatiit/musclex#15]
![7 ithh ugzz f9e8n591](https://user-images.githubusercontent.com/33042231/39319028-706ceb28-4945-11e8-91cd-fba24e55439c.png)
Fixed Sigma S/C et al were invisible. I would just delete Fixed, and use Sigma symbol if necessary. 

I would like another checkbox to fix the R-min, or remember previous value

**Comment by XintianLee** [comment]
Weikang,

Could you please tell me which exact program this is in musclex?

Xintian

**Comment by WeikangMa** [comment]
Fixed Sigma S/C et al were invisible. I would just delete Fixed, and use Sigma symbol if necessary. 
This is on the second tab (fitting) of equator.

I would like another checkbox to fix the R-min, or remember previous value
this is for both equator and QF program

**Comment by XintianLee** [comment]
Done in v1.13.8.
