### ISSUE TITLE
 Quadrant fold problem detected in 2D convex hull

### ISSUE THREAD

**Issue by iitbiocat** [biocatiit/musclex#24]
Quadrant fold has a problem with the 2D convex hull:

Image : 2015-1_010.tif

Error : <type 'exceptions.IndexError'>

Traceback (most recent call last):
  File
"/usr/local/lib/python2.7/dist-packages/musclex/ui/QuadrantFoldingGUI.py",
line 1773, in processImage
    self.quadFold.process(flags)
  File"/usr/local/lib/python2.7/dist-packages/musclex/modules/QuadrantFolder.py>
line 128, in process
    self.applyBackgroundSubtraction()
  File"/usr/local/lib/python2.7/dist-packages/musclex/modules/QuadrantFolder.py>
line 787, in applyBackgroundSubtraction
    self.apply2DConvexhull()
  File"/usr/local/lib/python2.7/dist-packages/musclex/modules/QuadrantFolder.py>
line 639, in apply2DConvexhull
    hist_y = list(I[hist_x])
IndexError: index 2685 is out of bounds for axis 1 with size 2685

**Comment by XintianLee** [comment]
It should be fixed in release 1.13.9. Please test it to see if it works.
