### ISSUE TITLE
Scanning Diffraction issues on Ubuntu (from Rama)

### ISSUE THREAD

**Issue by iitbiocat** [biocatiit/musclex#28]
The following observed on 13.10 for Scanning Diffraction running on Ubuntu:
1. Program crashing when loading a case of 1D scans (i.e. a single row of scans)
2. There were several warning on install (whereas in the previous warnings there were no warnings
3. When selecting to load a single image instead of a complete folder the image is not showing
4. The stop button (stopping the processing of the current directory) does not work
5. Some graphs do not update on parameter change
6. The new Herman orientation detection fails in some cases

**Comment by rama-sashank** [comment]
More observations on 1.13.10

**Bugs** 

1. Select peaks manually doesn't work. It applies to the first image in the series and the program reverts to full Rmin to Rmax for the rest of the folder.
2. We are converting pixel distance for reflections to d-spacing values. This is one of the functionalities that can be useful while looking at different types of constitutents in the tissue. 
	2.1. In the csv writeout we currently list this parameter as “center(nn)”. Can we change this to something more user friendly, like “D-spacing (nm)” or even “D(nm)”. Also the “nn” I believe is for nanometers, which was mislabeled. So we should change that to “nm”.

**Questions**
1. When we apply only Rmin and Rmax and no ROI, what does the program default to for ROI? The Rmin and Rmax?
2. 	More information on the 2 types of integration the program is doing, or what it is defaulting to. This is a documentation issue, I believe. 
3. 	Are we incorporating any sort of an internal check as to validate the alignment we find using any of the current methods (GMM2,GMM3 or Herman factor)?

**Comment by rama-sashank** [comment]
These issues have been resolved. Please close this issue.
