### ISSUE TITLE
Musclex eq orientation finding now not working properly

### ISSUE THREAD

**Issue by tomirving** [biocatiit/musclex#29]
in 1.13.11. 
Perhaps something went wrong when new algorithms propagated.

**Comment by iitbiocat** [comment]
Hi,

From the traceback information you sent me, I can see that the error occurred when importing **PyMca5**.
```
Traceback (most recent call last):
  File "/usr/local/bin/musclex", line 11, in <module>
    sys.exit(main())
  File "/usr/local/lib/python2.7/dist-packages/musclex/main.py", line 47, in main
    from musclex.ui.EQStartWindow import EQStartWindow
  File "/usr/local/lib/python2.7/dist-packages/musclex/ui/EQStartWindow.py", line 35, in <module>
    from ..ui.EquatorWindow import EquatorWindow
  File "/usr/local/lib/python2.7/dist-packages/musclex/ui/EquatorWindow.py", line 45, in <module>
    from .BlankImageSettings import BlankImageSettings
  File "/usr/local/lib/python2.7/dist-packages/musclex/ui/BlankImageSettings.py", line 40, in <module>
    import PyMca5.PyMca.MaskImageWidget as PyMcaMaskImageWidget
  File "/usr/local/lib/python2.7/dist-packages/PyMca5/PyMcaGui/plotting/MaskImageWidget.py", line 33, in <module>
    from PyMca5.PyMcaGraph.ctools import pnpoly
  File "/usr/local/lib/python2.7/dist-packages/PyMca5/PyMcaGraph/ctools/__init__.py", line 36, in <module>
    from _ctools import *
ImportError: /usr/local/lib/python2.7/dist-packages/PyMca5/PyMcaGraph/ctools/_ctools.so: undefined symbol: PyFPE_jbuf
```
Perhaps, you need to upgrade **PyMca5** by running
```
pip install -U PyMca5
```
Also, I saw a lot of runtime warnings before this error traceback. They are caused by the new release of **numpy** (1.15.0). If you want to get rid of these warnings for now, you can install a previous version of **numpy** instead, for example,
```
pip install numpy==1.14.5
```

Thanks,
Xintian

**Comment by tomirving** [comment]
I'll give it a try.
Tom

Thanks,
Tom Irving

**Comment by tomirving** [comment]
What's puzzling is that nominally identical distros have different failure
modes. Seems to matter if it is a fresh install of a distro or an upgrade.
Tom Irving

Thanks,
Tom Irving

**Comment by tomirving** [comment]
Reinstalling PyMca didn't help although downgrading numpy got rid of the
error messages.
This is on a machine that was upgraded from 16.04 to 18.04 and had previous
versions of musclex installed
I have a virtual machine on my mac where I did a fresh install of 18.04 and
I don't have this problem. I had a different problem is that the stoock pip
didn't work and I had to manually install
the most recent version of pip to work.
It still looks like when we propagated the orientation finding stuff to
equator in 1.13.11, it no longer works properly i.e. doesn't find the
correct orientation.
I haven't had tiem to investigate the other propograms yet.

Thanks
Tom Irving

Thanks,
Tom Irving

**Comment by XintianLee** [comment]
I am installing Ubuntu 18.04 to check the problem.

For the orientation finding, 1.13.11 retains the original method as *Max Intensity* option. This option should work exactly the same as before. I tested **Equator** on some images before release 1.13.11, and *Max Intensity* and *GMM* worked fine. But *Herman Factor* option could not give the right orientation. I can show you the test results in a report later.

Thanks,
Xintian

**Comment by tomirving** [comment]
I tried equator using 1.13.8 on a 16.04 machine and it worked properly. I
then updated to 1.13.11 and I have the same problem that  and it failed to
find the orientation as it did on my 18.04 machine. I was able to
successfully downgrade to 1.13.10 ( which I wasn't able to do on the 18.04
machine) and the oritentation works. SO soemthing happened to equator with
1.13.11
Thanks
Tom Irving

Thanks,
Tom Irving

**Comment by tomirving** [comment]
Any other ideas as to how I might fix the pyMCA problem? I would like to
use this machine for data analysis. I tried various things like deleting
versions of pymca that were in /usr/local/bin
I am a bit reluctant to do a clean install of 18.04 on this machine since I
would lose a bunch of stuff but I am heading in that direction.
Thanks
Tom

Thanks,
Tom Irving

**Comment by XintianLee** [comment]
I noticed that in our documentation of installation by pip pyFAI is installed by `apt-get`. So if you install pyFAI in this way, you can first remove it by running
```
sudo apt-get remove pyfai
```
and then install it by pip
```
sudo pip install -U pyfai
```
or
```
sudo python -m pip install -U pyfai
```
Hope this can help.

Thanks,
Xintian
