### ISSUE TITLE
dc doesn't remember the zoom in traces from previous image

### ISSUE THREAD

**Issue by WeikangMa** [biocatiit/musclex#3]
It used to remember the zoom in traces from previous iamge. most of the time I only care about certain range. Being able to see the magnified traces helps me.

**Comment by jiranun** [comment]
Will be fixed in the next release.

Thanks,
Jiranun

**Comment by WeikangMa** [comment]
Thanks. please also let the program remember the manually selected convexhull range from previous image

**Comment by jiranun** [comment]
The convexhull range has been added in [version 1.4](https://github.com/biocatiit/musclex/wiki/Version-1.4). Please let me know if it does not work.

Thanks

**Comment by WeikangMa** [comment]
I am using the dc v.1.4.2. I have to select the range fro each image now

**Comment by jiranun** [comment]
I will fix that in the next release too. Thanks

**Comment by jiranun** [comment]
However, I encourage you to use Projection Traces instead of Diffraction Centroids because we might not support Diffraction Centroids anymore in the future as Projection Traces can do everything Diffraction Centroids can

**Comment by WeikangMa** [comment]
good point

**Comment by jiranun** [comment]
I just found that in version 1.4 convex hull range will be remembered only for off meridian diffraction. 

Now, both issues here are fixed in version 1.5. Click [here](https://github.com/biocatiit/musclex/wiki/Version-1.5) for release note 

Reopen the issue if you get any problem.

Thanks
