### ISSUE TITLE
1.14.0 - DI- Issues with setting R-min and R-max

### ISSUE THREAD

**Issue by rmadhura-iit** [biocatiit/musclex#34]
I am not able to set the R-min and R-max on DI. Attached is a screenshot of the error, along with the error output on CLI. 

I also included the error code here. 

`Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/matplotlib/cbook/__init__.py", line 387, in process
    proxy(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/matplotlib/cbook/__init__.py", line 227, in __call__
    return mtd(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/musclex/ui/CPImageWindow.py", line 752, in imgClicked
    self.ROI[0] = max(rmin, self.ROI[0])
TypeError: 'NoneType' object has no attribute '__getitem__'
`
![1 14-rminrmax-settingissue](https://user-images.githubusercontent.com/43549103/45967173-c8673d00-bff2-11e8-8b1a-768d2932ae53.png)

**Comment by rmadhura-iit** [comment]
More issues:

When i click "Process Entire Folder", after running through a few images, processing stops with the following error message:

`Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/musclex/ui/CPImageWindow.py", line 869, in batchProcBtnToggled
    self.processFolder()
  File "/usr/local/lib/python2.7/dist-packages/musclex/ui/CPImageWindow.py", line 942, in processFolder
    self.nextImage()
  File "/usr/local/lib/python2.7/dist-packages/musclex/ui/CPImageWindow.py", line 1115, in nextImage
    self.onImageChanged()
  File "/usr/local/lib/python2.7/dist-packages/musclex/ui/CPImageWindow.py", line 1029, in onImageChanged
    self.processImage()
  File "/usr/local/lib/python2.7/dist-packages/musclex/ui/CPImageWindow.py", line 1042, in processImage
    self.updateUI()
  File "/usr/local/lib/python2.7/dist-packages/musclex/ui/CPImageWindow.py", line 1094, in updateUI
    self.updateImageTab()
  File "/usr/local/lib/python2.7/dist-packages/musclex/ui/CPImageWindow.py", line 1255, in updateImageTab
    model = self.cirProj.info['average_ring_model']
KeyError: 'average_ring_model'
`

**Comment by rmadhura-iit** [comment]
I had to revert to 1.13.11 because analysis would halt at a certain image, different one each time, and wouldnt let me go forward.

**Comment by XintianLee** [comment]
Hi,

I have just fixed these two bugs in the 1.14.1 release. Please check that.

Thanks

**Comment by rmadhura-iit** [comment]
Hi, 
I upgraded to 1.14.1. The calibration settings function seems to be broken. The initial readout is fine. The program detects and center based on rings, but when I choose a calibrant (Silver behenate in this instance), and chose the ring to calibrate against, the settings are not getting updated, and the center moves to a the same spot, that is not the center, as you can see in the screenshot here - The little white dot on the bottom left of the screen is the detected center after doing the calibration.  

This was never a problem in previous versions. 

![1 14 1-calibrationissue](https://user-images.githubusercontent.com/43549103/46354998-81e29580-c625-11e8-8c48-9d3cc90fd844.png)

**Comment by XintianLee** [comment]
Hi,
Can you send a copy of this image to me? I'm sure that in the latest several releases the calibration part has not been modified. By the way, finding center is the first thing done in the analysis, so the center is not detected based on rings.
Thanks.

**Comment by rmadhura-iit** [comment]
I sent the calibration file to you over email because GitHub does not accept tif files here.

**Comment by rmadhura-iit** [comment]
I have also not noticed this error until just now, but since 1.13.11 there seems to a be a problem with persistence when we use the "Select Rings Manuall" option. The selection is applied only to the current image and when I click the "Process Entire Folder" button, the program defaults to R-min and R-max.

**Comment by XintianLee** [comment]
Hi,

I'm not sure if I tested right as you did. 

Scanning Diffraction test on `AgBeh-0725-Shot1_0001.tif`.
1. original result without calibration
![image](https://user-images.githubusercontent.com/23442847/46896547-36a95d80-ce43-11e8-94ab-e8d68fe388b2.png)
2. setting by calibration image
- before
![image](https://user-images.githubusercontent.com/23442847/46896683-01e9d600-ce44-11e8-9bdc-8530a8c3eb95.png)
- after
![image](https://user-images.githubusercontent.com/23442847/46896721-42495400-ce44-11e8-8994-ee8cfaae1855.png)
3. result with calibration
![image](https://user-images.githubusercontent.com/23442847/46896791-b97ee800-ce44-11e8-8154-3dad1aa0f943.png)
  the result looks the same as before, but we can see the differences in the console.

As for the persistence of "Select rings manually", I think it has never been supported so far.

Thanks.
