### ISSUE TITLE
experience of docker install on Windows machines 

### ISSUE THREAD

**Issue by fischcheng** [biocatiit/musclex#4]
Thanks for the heavylifting!
I am very excited to see the Docker install, it will truly make this package cross-platforms. However, it took me a while to get the Docker install done on Windows, so I figure might be a good idea to document some of the experiences.

* The new native Docker for Windows only supports Windows 10 Pro (with Hyper-V enabled).
* All other versions of Windows, you need to use Docker Toolbox (a package containing docker engine, docker machine, virtual box, Kitematic(GUI docker)or so). Basically it create a virtual machine to run docker.
* This lead to another issue: $Display setting, on a native Linux, the current docker install uses "xhost", which is not available on this VirtualBox. 
* Install the X11 server on Windows, e.g. Xming
* Find the IP that the Windows machine connected to the docker-machine: in my case 192:168:99:1 
* Add this IP to the DISPLAY variable in musclex.sh: `DISPLAY=192.168.99.1:0`
* Run `./musclex options`, your program now will pop up on your screen.

**Comment by jiranun** [comment]
Thanks a lot Fisch! 
Thanks
Tom
