### ISSUE TITLE
1.14.10 - DI - 1-D map display

### ISSUE THREAD

**Issue by rmadhura-iit** [biocatiit/musclex#45]
In 1D scans, once all the integration is done, and we generate a heatmap stitch of the scan, the diffraction pattern is not being displayed on the left side of the window, when we click on the pixel on the map. 

![image](https://user-images.githubusercontent.com/43549103/60914268-cce1a700-a24e-11e9-865a-70bb1b7010ad.png)

Also, we are not able to export the 1D map to either PNG or SVG. Here is the error message from the console. 
`
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/musclex/ui/CPBatchWindow2.py", line 488, in saveClicked
    if filename.split('.')[1] == 'svg':
IndexError: list index out of range
`

**Comment by rmadhura-iit** [comment]
The PNG/SVG write out is working if we manually append .png or .svg in the file name after selecting the respective filetype. 
This can be documented.

**Comment by grantnikseresht** [comment]
When running with MuscleX 1.14.11 on Docker, this display feature appears to be working fine. There should not be any changes to DI between 1.14.10 and 1.14.11, but perhaps you could try again now that the Docker image has updated to 1.14.11. Could you point me to the images you're having issues with for me to test?

I think the PNG/SVG issue is some cross-platform issue, I changed the format checking functionality in the new version. Let me know if you have issues with saving files in the future.
