### ISSUE TITLE
Can you add the peak intensity coordinate

### ISSUE THREAD

**Issue by WeikangMa** [biocatiit/musclex#5]
Hi:
Can you add the peak intensity coordinate on pt. 
![peak](https://user-images.githubusercontent.com/33042231/33910245-aadc3c34-df53-11e7-9888-9755ee1b295c.png)
The position of maximum intensity

**Comment by jiranun** [comment]
Will do.

Thanks.

**Comment by jiranun** [comment]
Hi Weikang,

I have some questions.
1. Do you want them to be displayed on the graph or display as numbers on the right panel or both?
2. Do you want this information in the cvs file?

While you're waiting for the new version, you can put the cursor at the peak, then you will see distance from center at the bottom right (status bar).

Thanks

**Comment by jiranun** [comment]
This feature has been added to Muscle X version [1.9](https://github.com/biocatiit/musclex/wiki/Version-1.9)

Feel free to reopen the issue if you need any assistance

Thanks
