### ISSUE TITLE
padding images

### ISSUE THREAD

**Issue by ttune3** [biocatiit/musclex#53]
On some images we have the a6 is in 3 of the four quadrants. When I do quadrant folding on them it makes the a6 impossible to pick out. I tried padding the image with a border so that musclex would include those areas and the a6 comes out much better, but then there are black lines which run through the image which make running the projection trace and diffraction centroid programs not work as well. I think it also messes up the back ground subtraction. 

Basically I would like the option of padding the perimeter of the image a certain amount in order for muslex quadrant folder to pick out peaks not in every quadrant. 

![p31_wl5_00_folded-1](https://user-images.githubusercontent.com/25534432/62583329-c5c5ad00-b87d-11e9-94ab-6908e5e23498.jpg)
![p31_wl5_00_folded](https://user-images.githubusercontent.com/25534432/62583336-cbbb8e00-b87d-11e9-9454-8cf65cdea149.jpg)

I think the problem is that musclex uses the size of the image to determine what detector the image was taken on? I uploaded the images as .jpg, I can email the .tifs if its helpful to you.

Best, 

Travis Tune

**Comment by grantnikseresht** [comment]
We're going to add automatic image padding whenever the image is rotated in the next version (14.13), which may solve this issue. The padding should eliminate problems related to chopping off parts of the image when it's rotated multiple times. I'll follow up once it's out, so you can test it and provide feedback.

**Comment by ttune3** [comment]
Great! That sounds really good. When do you think you'll be able to release the next version?

**Comment by ttune3** [comment]
Would it also be possible have musclex also crop images to a certain size after they are folded? Currently once images get folded, they can end up being any size depending on how the image is oriented. But it would be convenient if they came out a standardized size. 

Also, when you load a folded image into diffraction centroid, it tries to find the center and equator, but sometimes it gets it wrong. But if the image is already folded it shouldn't have to since it should already be aligned.
