### ISSUE TITLE
14.12PT

### ISSUE THREAD

**Issue by WeikangMa** [biocatiit/musclex#54]
1:The  calibration option doesn't work. Once I chose to load calibration, the calibration appeared on mainscreen and replaced the actual muscle pattern.(low priority for now)
2: the center finding is off. The peaks are symmetrical and strong, but the program found the wrong center 
I will test the rest of functions once this problems are fixed

**Comment by rmadhura-iit** [comment]
This is not a problem for me. I was able to calibrate and run analyses. Center finding seems to be working fine, and peak detection is working as expected.

**Comment by WeikangMa** [comment]
ok, thanks for the information. I probably didn't do it right. I will test it more
