### ISSUE TITLE
Backgroundor calibration image upload crashes muscle X programs

### ISSUE THREAD

**Issue by HesselAL** [biocatiit/musclex#57]
Uploading calibration or background images crashes the MuscleX programs. I use the Windows version, version 14.4 (downloaded 4 days ago). The crash is just the program terminating.

**Comment by nikhilpmiskin** [comment]
Can you send the log file associated with the crash?

**Comment by HesselAL** [comment]
Hi,
Thank you for the response! In preparation for this email, I found that the background image is corrupt! This seems to be making the system crash. It turns out that when we download the pictures from the server at APS, images can corrupt, however, they are OK when viewed at APS. We have found a workaround for this. I tried other random images, and it seems to be OK.  The calibration image was  not corrupt, and was causing the system to crash. However, it is currently not doing it. Perhaps it is because I changed where on my computer I save the calibration file? Either way, I will get Weikang to send me a non-corrupt background image and see if all works! I will keep you updated. Thanks! Anthony
