### ISSUE TITLE
Equator manual calibration input

### ISSUE THREAD

**Issue by HesselAL** [biocatiit/musclex#58]
This pertains to the equator program. It is not possible to input a S-factor larger than 5000. We have a number of ~7800. When we input 780, we get a D10 of 4.04 which should be 40.4. We use the windows version, downloaded Feb 26. Thank you.

**Comment by nikhilpmiskin** [comment]
Can you provide a screenshot which describes your issue?

**Comment by HesselAL** [comment]
![image1](https://user-images.githubusercontent.com/61580609/76839617-1a7ace80-6836-11ea-996d-934210e0dfe6.png)

The Sdd value does not allow values much bigger than 2500. My value is 7800. However, when I use the calibration file, it calculates all OK. So not an immediate problem anymore! Anthony
