### ISSUE TITLE
Muscle X stops on Mac OS

### ISSUE THREAD

**Issue by kphqq** [biocatiit/musclex#60]
I installed Muscle X and tried to launch Quadrant Folding, but it didn't start running. What I could see was this error massage. (I attached the screen shot and the error file.)
I'm using Mac OS 10.15.5 Catalina. I tried following versions of Muscle X: "musclex-1.14.12 (OS X 10.9).dmg", "musclex-1.14.4 (macOS 10.12.6).dmg","musclex-1.14.3 (macOS 10.9).dmg","musclex-1.14.3 (macOS 10.12.6).dmg", "musclex-1.13.4 (OS X 10.9).dmg", "musclex-1.13.4 (OS X 10.12).dmg", "musclex-1.13.3.dmg". The same error happened with all versions above.

[musclex.error.log](https://github.com/biocatiit/musclex/files/5482195/musclex.error.log)

![IMG_5601](https://user-images.githubusercontent.com/38066697/98004701-9496ac80-1e33-11eb-8b99-3a1c171c9e2e.PNG)

**Comment by fischcheng** [comment]
Found some clue on this, seems to be a known issue for OSX PyOpenCL, and here is a way to get past the error.
https://stackoverflow.com/questions/53015295/pyopencl-fails-to-build-program-on-macos-mojave

here is the gist:
```
export PYOPENCL_NO_CACHE=1
open /Applications/musclex.app/Contents/MacOS/musclex-launcher
```

Might have to change the path to the launcher. Pack it into a file, and execute the file, your `musclex` will work as expected.
