### ISSUE TITLE
Missing row of pixels

### ISSUE THREAD

**Issue by gpfarman** [biocatiit/musclex#77]
On the latest release of MuscleX some of the images have a missing row (i.e. 2047x2048 instead of 2048x2048). This isn't a huge issue unless you are trying to average images together. Not sure why this happens but people should know just in case. FYI this is the MacOS version of the software (1.21.1).

**Comment by Julesnab** [comment]
Can you give me more details on when this happened? I suppose it is when you use Quadrant folder, but is it happening systematically? Is there a particular way to reproduce the problem?

**Comment by gpfarman** [comment]
Hi Jules,

This is a completely random event that occurs when you are Quadrant folding. I was averaging some images together and ImageJ would randomly tell me the images weren’t not the same size. At first I thought it was my fault since it was happening on images I was manually folding and I thought I was going to fast with the advance key but I noticed the same issue with files that I had let the program do automatically. This might be a big deal when I start averaging images from time resolved studies since I need to use my Mac to do the folding at this time. If you want I can send some example images to you.


__________________________
Gerrie P. Farman Ph.D.

Assistant Research Scientist
Gregorio/Granzier Labs
Sarver Heart Center
Cellular and Molecular Medicine
1656 E. Mabel St.
Room 340
Tucson, AZ 85719

On Apr 4, 2023, at 7:35 AM, Jules Nabon ***@***.******@***.***>> wrote:


External Email


Can you give me more details on when this happened? I suppose it is when you use Quadrant folder, but is it happening systematically? Is there a particular way to reproduce the problem?

**Comment by Julesnab** [comment]
Okay thank you for your answer. There might be a pattern creating this problem, I will look at it as soon as possible and I will let you know whenever it is fixed. 
And yes if you have examples you don't mind sharing with me, it would be helpful. Thank you again.

**Comment by gpfarman** [comment]
The files are rather large 12 mb compressed so if you have a way to transfer data I’ll gladly send over say three of the “bad” files and three “good” files.


__________________________
Gerrie P. Farman Ph.D.

Assistant Research Scientist
Gregorio/Granzier Labs
Sarver Heart Center
Cellular and Molecular Medicine
1656 E. Mabel St.
Room 340
Tucson, AZ 85719

On Apr 4, 2023, at 10:35 AM, Jules Nabon ***@***.******@***.***>> wrote:


External Email


Okay thank you for your answer. There might be a pattern creating this problem, I will look at it as soon as possible and I will let you know whenever it is fixed.
And yes if you have examples you don't mind sharing with me, it would be helpful. Thank you again.
