### ISSUE TITLE
calibration for quadrant folder

### ISSUE THREAD

**Issue by tomirving** [biocatiit/musclex#9]
It would be useful to have the same calibration tool that is in equator available in quadrant folder. If it is there, I couldn't find it...

Tom

**Comment by jiranun** [comment]
Calibration Settings will provide calibration parameters and center. The useful thing from calibration settings for Quadrant Folding is only center, so I didn't add this feature to QF. However, you can set manual center in the Image tab.

Thanks,
Jiranun

**Comment by jiranun** [comment]
I will do the 2 clicks function in the calibration settings and then add the settings to QF. I will have time this weekend.

Thanks
Jiranun

**Comment by tomirving** [comment]
Cool!


Thanks,
Tom Irving

**Comment by jiranun** [comment]
Calibration settings button has been added to version 1.12. The two-click calibration is being implemented.

Thanks
